### ISSUE TITLE
re: Dedicated Node

### ISSUE THREAD

**Issue by robinson20** [NewYorkCoin-NYC/nycoin#20]
Good day Dev,

i have a static IP and want to run a dedicated node, it is there to do just that. I would like to spin up a dedicated node. My  IPv4 address is 10.0.0.157 , If  you need additional info please let me know.
My email address is : pluto3480@yahoo.com
thanking you in advance,

Jeffrey

**Comment by jamesburrell2** [comment]
Talk to Hobbyist here or in Discord

**Comment by nycoins** [comment]
Why?

Alexander Nicholas
President
KEATS

**Comment by ltanyc** [comment]
Jeffrey, `10.0.0.157` is in a private IP address range so we can't use it as a peer node.
For more on reserved IP address range see [RFC 1918](https://tools.ietf.org/html/rfc1918).
