### ISSUE TITLE
Replace bitcoins with New York Coin in Encrypt Wallet message

### ISSUE THREAD

**Issue by zmintlimited** [NewYorkCoin-NYC/nycoin#25]
it says "bitcoins", it should be NYC

Using Mac OS X 10.13.6

![screen shot 2018-07-26 at 5 31 30 pm](https://user-images.githubusercontent.com/29587555/43243305-23562942-90fa-11e8-87be-52dcce886868.png)

**Comment by MrSlosh** [comment]
Yep, sure does. I will correct it. There are likely other instances in strings here and there. Good find.

**Comment by MrSlosh** [comment]
Pushed changes to the UI-text-changes branch. I will generate a pull request next week so there is a little more time to find and fix UI text issues.
