### ISSUE TITLE
Issue with OpenSSL

### ISSUE THREAD

**Issue by Cru1z** [NewYorkCoin-NYC/nycoin#34]
This package is part of the OpenSSL project's implementation of the SSL and TLS cryptographic protocols for secure communication over the Internet.

When compiling on RPi getting an error:
configure: error: Detected LibreSSL: This is NOT supported, and may break consensus compatibility!

configure: error: libdb_cxx headers missing, NewYorkCoin requires this library for wallet functionality (--disable-wallet to disable wallet functionality)

Unable to install wallet functionality

**Comment by Cru1z** [comment]
Tried it again with the latest build using libssl-dev

cd nycoin
./autogen.sh
./configure CPPFLAGS="-I/usr/local/BerkeleyDB.4.8/include -O2" LDFLAGS="-L/usr/local/BerkeleyDB.4.8/lib" --enable-upnp-default

Results in;
checking for visibility attribute... yes
checking for Berkeley DB C++ headers... no
**configure: error: libdb_cxx headers missing, NewYorkCoin requires this library for wallet functionality (--disable-wallet to disable wallet functionality)**

Then tried running it with;
./configure --enable-upnp-default --disable-wallet

Results in error;
**configure: error: Detected LibreSSL: This is NOT supported, and may break consensus compatibility!**

Only way around it I've found is to use libssl1.0-dev instead of libssl-dev and run it with --disable-wallet so I'm not able to get wallet functionality to work with this.  Berkley database and other dependencies are installed.

**Comment by nicovs** [comment]
ty.

`apt-get install libssl1.0-dev`
to replace the libssl-dev, and compile with 

`./configure --enable-upnp-default --disable-wallet`
helps.
(this is a server that doenst need the wallet function anyways.
