### ISSUE TITLE
:Feature Request: Build and release Linux binary files 

### ISSUE THREAD

**Issue by TravisBack** [NewYorkCoin-NYC/nycoin#43]
Even though the Raspberry Pi directions also work for building a node for Linux, there are no clear instructions for building a fully functional usable wallet for Linux.

**Comment by ltanyc** [comment]
have you tried the directions from `https://github.com/NewYorkCoin-NYC/nycoin/blob/master/doc/build-unix.md`?

**Comment by TravisBack** [comment]
> have you tried the directions from `https://github.com/NewYorkCoin-NYC/nycoin/blob/master/doc/build-unix.md`?

Yup, used those directions as well. No matter what I tired, I kept getting different build errors and version conflicts if I didn't use --disable-wallet under Ubuntu Server 18.04.2

I'd be happy with updated COMPLETE instructions for compiling on 18.04.2 (fresh install)

**Comment by Cointopaydev** [comment]
Thread 1 "newyorkcoind" received signal SIGSEGV, Segmentation fault.
0x00007ffff5792dfa in strlen () from /lib/x86_64-linux-gnu/libc.so.6

**Comment by Cointopaydev** [comment]
#0  0x00007ffff5792dfa in strlen () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff70d8da2 in __os_strdup () from /usr/lib/x86_64-linux-gnu/libdb_cxx-5.1.so
#2  0x00007ffff70ad662 in __env_add_data_dir () from /usr/lib/x86_64-linux-gnu/libdb_cxx-5.1.so
#3  0x00007ffff70ad731 in __env_set_data_dir () from /usr/lib/x86_64-linux-gnu/libdb_cxx-5.1.so
#4  0x00007ffff6fd1bbc in DbEnv::set_data_dir(char const*) () from /usr/lib/x86_64-linux-gnu/libdb_cxx-5.1.so
#5  0x00005555557d6631 in CDBEnv::Open (this=0x555555c729e0 <bitdb>, pathIn=...) at wallet/db.cpp:92
#6  0x0000555555815852 in CWallet::Verify (walletFile="wallet.dat", warningString="", errorString="") at wallet/wallet.cpp:354
#7  0x00005555555ab67e in AppInit2 (threadGroup=..., scheduler=...) at init.cpp:987
#8  0x0000555555591c4d in AppInit (argc=<optimized out>, argv=<optimized out>) at bitcoind.cpp:147
#9  0x000055555558894f in main (argc=1, argv=0x7fffffffe6d8) at bitcoind.cpp:176

**Comment by Cointopaydev** [comment]
has something to do with incompatible bdb

**Comment by ltanyc** [comment]
I'm able to build using these step on ubuntu 18.04:
```
sudo apt-get install  build-essential libtool autotools-dev autoconf pkg-config openssl1.0-dev libboost-all-dev libdb5.3-dev libdb5.3++-dev pkg-config libtool
./autogen.sh
./configure --enable-peers --with-incompatible-berkeleydb
make
make install
```

**Comment by cmelion** [comment]
Closing this.  Posting binaries exposes users to potential risk.  For Windows and Mac the difficulty in building outweighs the risk.  For linux we encourage all users to build from source or use the docker build process.  Long term goal is to make the build process simpler.
